#  █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
# ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
# ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
# ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
# ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝
# A cross-platform, OpenGL terminal emulator.
# https://alacritty.org

live_config_reload: true

env:
  TERM: xterm-256color

font:
  normal:
    family: "OperatorMono Nerd Font"
    style: "Book"
  italic:
    family: "OperatorMono Nerd Font"
    style: "Book Italic"
  bold:
    family: "OperatorMono Nerd Font"
    style: "Bold"
  bold_italic:
    family: "OperatorMono Nerd Font"
    style: "Bold Italic"
  size: 20
  offset:
    x: 0 # For letter spacing (default: 0).
    y: 0 # For line spacing (default: 0).

window:
  opacity: 1.0

  padding:
    x: 10
    y: 10
  dynamic_padding: false

  # full: Title bar, transparent background and title bar buttons
  # none: Neither borders nor title bar
  # transparent: Title bar, transparent background and title bar buttons
  # buttonless: Title bar, transparent background and no title bar buttons
  decorations: buttonless

  # Make `Option` key behave as `Alt` (macOS only):
  #   - OnlyLeft
  #   - OnlyRight
  #   - Both
  #   - None (default)
  option_as_alt: Both

# NOTE: helpful hex codes
# \x1b = escape (useful for vim-related keybindings)
# \x01 = control-a
# \x1A = control-z
# check https://www.physics.udel.edu/~watson/scen103/ascii.html

key_bindings:
  - { key: Key1, mods: Command, chars: "\x1A1" } # select tmux window 1
  - { key: Key2, mods: Command, chars: "\x1A2" } #                ... 2
  - { key: Key3, mods: Command, chars: "\x1A3" } #                ... 3
  - { key: Key3, mods: Alt, chars: "#" } #                ... #
  - { key: Key4, mods: Command, chars: "\x1A4" } #                ... 4
  - { key: Key5, mods: Command, chars: "\x1A5" } #                ... 5
  - { key: Key6, mods: Command, chars: "\x1A6" } #                ... 6
  - { key: Key7, mods: Command, chars: "\x1A7" } #                ... 7
  - { key: Key8, mods: Command, chars: "\x1A8" } #                ... 8
  - { key: Key9, mods: Command, chars: "\x1A9" } #                ... 9
  - { key: Comma, mods: Command, chars: "\x1A," } # rename the current tmux window
  - { key: E, mods: Command, chars: "\x1A|" } # split tmux window vertically
  - { key: E, mods: Command|Shift, chars: "\x1A-" } # split tmux window horizontally
  - { key: F, mods: Command|Shift, chars: "\x1A\x5b\x2f" } # start tmux search mode
  - { key: F, mods: Command, chars: "lf\n" } # open file manager 'gokcehan/lf'
  - { key: G, mods: Command, chars: "\x1Ag" } # open git manager 'jesseduffield/lazygit'
  - { key: J, mods: Command, chars: "t\n" } # open t - tmux smart session manager
  - { key: K, mods: Command, chars: "\x1As" } # open interactive tmux session client
  - { key: L, mods: Command, chars: "\x1AL" } # switch to the last tmux session
  - { key: LBracket, mods: Command, chars: "\x0f" } # navigate back (ctrl+o)
  - { key: LBracket, mods: Command|Shift, chars: "\x1Ap" } # switch to next tmux window
  - { key: O, mods: Command, chars: "\x1Au" }
  - { key: P, mods: Command, chars: ":GoToFile\n" } # files
  - { key: P, mods: Command|Shift, chars: ":GoToCommand\n" } # commands
  # - { key: Period, mods: Command, chars: "\x1b\x20\x2e\x0a" } (causes popup to be unfocused)
  - { key: Q, mods: Command, chars: ":q\n" } # quit vim
  - { key: R, mods: Command, chars: "\x1b\x5b\x41\x0a" }
  - { key: RBracket, mods: Command, chars: "\x09" }
  - { key: RBracket, mods: Command|Shift, chars: "\x1An" }
  - { key: S, mods: Command, chars: "\x1b\x3a\x77\x0a" } # save vim buffer
  - { key: S, mods: Command|Shift, chars: ":wa\n" } # save all
  - { key: Semicolon, mods: Command, chars: "\x1A:" } # enter the tmux command prompt
  - { key: T, mods: Command, chars: "\x1Ac" } # create a new tmux window
  - { key: W, mods: Command, chars: "\x1Ax" } # kill the current pane
  - { key: Z, mods: Command, chars: "\x1Az" } # toggle zoom state of the current tmux pane

import:
  - "~/.dotfiles/config/alacritty/themes/catppuccin.yml"
