source "$DOTFILES/config/shell/alias.sh"
source "$DOTFILES/config/shell/exports.sh"
source "$DOTFILES/config/shell/funcs.sh"
source "$DOTFILES/config/shell/overrides.sh"
source "$DOTFILES/config/shell/startup.sh"
