# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
# The minimal, blazing-fast, and infinitely customizable prompt
# https://starship.rs

# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# Inserts blank line between shell prompts
add_newline = true
command_timeout = 3000

format = """\
$directory\
[](fg:blue bg:cyan)\
$git_branch\
$git_status\
[](fg:cyan bg:yellow)\
$cmd_duration\
[ ](fg:yellow)\
"""

[directory]
format = "[  $path ]($style)"
home_symbol = "~"
read_only = " 󰌾"
read_only_style = "fg:red bg:blue"
style = "fg:black bg:blue"
truncate_to_repo = true
truncation_length = 2
truncation_symbol = '…/'

[git_branch]
disabled = false
format = "[ $symbol$branch(:$remote_branch) ]($style)"
style = "fg:black bg:cyan"
symbol = "󰘬 "
truncation_length = 20
truncation_symbol = "…"

[git_status]
ahead = ' ${count}'
behind = ' behind=${count}'
conflicted = ' ${count} '
deleted = '󰍶 ${count} '
disabled = false
diverged = ' ${ahead_count}  ${behind_count}'
format = '[$all_status]($style)'
modified = '󰛿 ${count} '
renamed = '󱍸 ${count} '
staged = '󰐗 ${count} '
stashed = ' ${count} '
style = "fg:black bg:cyan"
untracked = '󰋗 ${count} '
up_to_date = '󰘽 '


[cmd_duration]
format = '[  $duration ]($style)'
min_time = 2000
style = "fg:black bg:yellow"
