format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[directory]
format = "[ $path]($style) "
style = "blue bold"

[character]
disabled = false
success_symbol = "[](purple)"
error_symbol = "[](red)"
vimcmd_symbol = "[](green)"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "bright-black"
symbol = " "
truncation_length = 20
truncation_symbol = "…"

[git_status]
ahead = ' ${count}'
behind = ' behind=${count}'
conflicted = ' ${count} '
deleted = '󰍶 ${count} '
disabled = false
diverged = ' ${ahead_count}  ${behind_count}'
format = '[$all_status]($style)'
modified = '󰛿 ${count} '
renamed = '󱍸 ${count} '
staged = '󰐗 ${count} '
stashed = ' ${count} '
style = 'cyan'
untracked = '󰋗 ${count} '
up_to_date = '󰘽 '

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"
