# Main Colors
unrecognized_file: "#FA8D3E" # Orange
recognized_file: "#cccac2" # Foreground
executable_file: "#d5ff80" # Green
dir: "#73d0ff" # Blue

# Link
dead_link: "#f28779" # Red
link: "#95e6cb" # Cyan

# Special Files
socket: "#d5ff80" # Green
blockdev: "#d5ff80" # Green
chardev: "#d5ff80" # Green

# Access Modes
write: "#d699b6" # Pink
read: "#dfbfff" # Magenta
exec: "#95e6cb" # Cyan
no_access: "#f28779" # Red

# Age
hour_old: "#cccac2" # Foreground
day_old: "#6C7A8B" # Comment
no_modifier: "#cccac2" # Foreground

# File Size
file_large: "#f28779" # Red
file_medium: "#FA8D3E" # Orange
file_small: "#d5ff80" # Green

# Random
report: "#d5ff80" # Green
user: "#95e6cb" # Cyan
tree: "#dfbfff" # Magenta
empty: "#6C7A8B" # Comment
error: "#f28779" # Red
normal: "#cccac2" # Foreground

# Git
addition: "#95e6cb" # Cyan
modification: "#facc6e" # Yellow
deletion: "#f28779" # Red
untracked: "#FA8D3E" # Orange
unchanged: "#d5ff80" # Green
