# Main Colors
unrecognized_file: "#ffeb95" # Yellow
recognized_file: "#d6deeb" # Foreground
executable_file: "#21c7a8" # Cyan
dir: "#82aaff" # Blue

# Link
dead_link: "#FF5874" # Red
link: "#7da6ff" # Bright Blue

# Special Files
socket: "#22da6e" # Green
blockdev: "#22da6e" # Green
chardev: "#22da6e" # Green

# Access Modes
write: "#c792ea" # Purple
read: "#c792ea" # Purple
exec: "#21c7a8" # Cyan
no_access: "#FF5874" # Red

# Age
hour_old: "#d6deeb" # Comment - 20% lighter
day_old: "#637777" # Comment
no_modifier: "#d6deeb" # Current Line

# File Size
file_large: "#FF5874" # Red
file_medium: "#ffeb95" # Yellow
file_small: "#22da6e" # Green

# Random
report: "#22da6e" # Green
user: "#21c7a8" # Cyan
tree: "#82aaff" # Blue
empty: "#637777" # Comment
error: "#FF5874" # Red
normal: "#d6deeb" # Foreground

# Git
addition: "#21c7a8" # Cyan
modification: "#addb67" # Bright Yellow
deletion: "#FF5874" # Red
untracked: "#ffeb95" # Yellow
unchanged: "#22da6e" # Green
