# One Dark themed dark color settings for colorls
#
# Main Colors
unrecognized_file: "#D19A66" # Orange
recognized_file: "#abb2bf" # Foreground
executable_file: "#56b6c2" # Cyan
dir: "#528bff" # Accent

# Link
dead_link: "#e06c75" # Red
link: "#61afef" # Blue

# Special Files
socket: "#98c379" # Green
blockdev: "#98c379" # Green
chardev: "#98c379" # Green

# Access Modes
write: "#c678dd" # Purple
read: "#c678dd" # Purple
exec: "#56b6c2" # Cyan
no_access: "#e06c75" # Red

# Age
hour_old: "#ABB2BF" # Comment - 20% lighter
day_old: "#5C6370" # Comment
no_modifier: "#323844" # Current Line

# File Size
file_large: "#e06c75" # Red
file_medium: "#D19A66" # Orange
file_small: "#98c379" # Green

# Random
report: "#98c379" # Green
user: "#56b6c2" # Cyan
tree: "#528bff" # Accent
empty: "#5C6370" # Comment
error: "#e06c75" # Red
normal: "#abb2bf" # Foreground

# Git
addition: "#56b6c2" # Cyan
modification: "#e5c07b" # Yellow
deletion: "#e06c75" # Red
untracked: "#D19A66" # Orange
unchanged: "#98c379" # Green
