# Main Colors
unrecognized_file: '#F78C6C' # Orange
recognized_file: '#969cc7' # Foreground
executable_file: '#89ddff' # Cyan
dir: '#82aaff' # Blue

# Link
dead_link: '#ff8b92' # Bright Red
link: '#9cc4ff' # Bright Blue

# Special Files
socket: '#c3e88d' # Green
blockdev: '#c3e88d' # Green
chardev: '#c3e88d' # Green

# Access Modes
write: '#c792ea' # Purple
read: '#c792ea' # Purple
exec: '#89ddff' # Cyan
no_access: '#ff8b92' # Bright Red

# Age
hour_old: '#969cc7' # Foreground
day_old: '#676E95' # Comment
no_modifier: '#969cc7' # Foreground

# File Size
file_large: '#ff8b92' # Bright Red
file_medium: '#F78C6C' # Orange
file_small: '#c3e88d' # Green

# Random
report: '#c3e88d' # Green
user: '#89ddff' # Cyan
tree: '#82aaff' # Blue
empty: '#676E95' # Comment
error: '#ff8b92' # Bright Red
normal: '#969cc7' # Foreground

# Git
addition: '#89ddff' # Cyan
modification: '#e0af68' # Yellow
deletion: '#ff8b92' # Bright Red
untracked: '#F78C6C' # Orange
unchanged: '#c3e88d' # Green
