# Main Colors
unrecognized_file: "#ae8a2d" # Yellow
recognized_file: "#b1cbcd" # Text
executable_file: "#8dc486" # Green
dir: "#4689cc" # Blue

# Link
dead_link: "#ca4238" # Red
link: "#519e97" # Cyan

# Special Files
socket: "#8dc486" # Green
blockdev: "#8dc486" # Green
chardev: "#8dc486" # Green

# Access Modes
write: "#8dc486" # Green
read: "#c24380" # Magenta
exec: "#519e97" # Cyan
no_access: "#ca4238" # Red

# Age
hour_old: "#b1cbcd" # Text
day_old: "#8f9f9f" # Gray
no_modifier: "#b1cbcd" # Text

# File Size
file_large: "#ca4238" # Red
file_medium: "#ae8a2d" # Yellow
file_small: "#8dc486" # Green

# Random
report: "#8dc486" # Green
user: "#519e97" # Cyan
tree: "#c24380" # Magenta
empty: "#8f9f9f" # Gray
error: "#ca4238" # Red
normal: "#b1cbcd" # Text

# Git
addition: "#519e97" # Cyan
modification: "#ae8a2d" # Yellow
deletion: "#ca4238" # Red
untracked: "#ae8a2d" # Yellow
unchanged: "#8dc486" # Green

