#!/usr/bin/env zsh

LP_ENABLE_JOBS=0
LP_ENABLE_HG=0
LP_ENABLE_SVN=0
LP_ENABLE_BATT=0
LP_ENABLE_BZR=0
LP_ENABLE_LOAD=0
LP_ENABLE_SCLS=0
LP_ENABLE_PROXY=0
LP_ENABLE_DIRSTACK=0
LP_ENABLE_TIME=1
LP_MARK_DIRSTACK="≣"
LP_PS1_POSTFIX=""
LP_DISABLED_VCS_PATHS=("$HOME/Projects/Magento/apps/oms")
