#!/usr/bin/env zsh

LP_ENABLE_JOBS=1
LP_ENABLE_HG=0
LP_ENABLE_SVN=0
LP_ENABLE_BATT=0
LP_ENABLE_BZR=0
LP_ENABLE_LOAD=0
LP_ENABLE_SCLS=0
LP_ENABLE_PROXY=0
LP_ENABLE_VIRTUALENV=0
LP_ENABLE_RUNTIME=
LP_ENABLE_PERM=1
LP_ENABLE_FOSSIL=0
LP_ENABLE_RUBY_VENV=0

# Dirstack settings
LP_ENABLE_DIRSTACK=0
LP_MARK_DIRSTACK="≣"

# Time settings
LP_ENABLE_TIME=0

# Path settings
LP_PATH_METHOD="truncate_chars_to_unique_dir"
LP_ENABLE_SHORTEN_PATH=1
LP_PATH_LENGTH=3

LP_PS1_POSTFIX=""
LP_DISABLED_VCS_PATHS=()
