#!/usr/bin/env zsh

# General
POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(custom_kube_context time command_execution_time status)
POWERLEVEL9K_DISABLE_RPROMPT=false
# POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="┌─"
# POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="└─▪ "
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="❯ "

# User segment
POWERLEVEL9K_USER_DEFAULT_FOREGROUND='white'
POWERLEVEL9K_USER_DEFAULT_BACKGROUND='black'
POWERLEVEL9K_USER_ICON="\ufb8a"
POWERLEVEL9K_ALWAYS_SHOW_USER=true

# Dir segment
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND='black'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='white'
POWERLEVEL9K_DIR_HOME_FOREGROUND='black'
POWERLEVEL9K_DIR_HOME_BACKGROUND='white'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND='black'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='white'
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_last
POWERLEVEL9K_HOME_ICON='\uf015 '
POWERLEVEL9K_HOME_SUB_ICON='\ufc6e '

# VCS
POWERLEVEL9K_VCS_BRANCH_ICON='\ufb2b '
VCS_GIT_GITHUB_ICON='\ue708'

# Status
POWERLEVEL9K_STATUS_CROSS=true

# Time
POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'

# Command execution
POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=1
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='black'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='yellow'

# Custom
POWERLEVEL9K_CUSTOM_KUBE_CONTEXT='custom_kube_context'
POWERLEVEL9K_CUSTOM_KUBE_CONTEXT_ICON='\u2388 '
POWERLEVEL9K_CUSTOM_KUBE_CONTEXT_BACKGROUND='blue'

# %F = foreground %K = background
custom_kube_context() {
  local color="%F{black}"
  [[ -z $ZSH_KUBECTL_CONTEXT ]] && return # Ensure that Kubectl context is defined
  [[ $ZSH_KUBECTL_USER =~ "admin" ]] && color='%F{red}'
  echo -n "%{$color%} $ZSH_KUBECTL_PROMPT%{%f%}"
}
