# https://github.com/navarasu/onedark.nvim/blob/master/lua/onedark/palette.lua
# Main Colors
unrecognized_file: "#dd9046" # Orange
recognized_file: "#93a4c3" # Fg
executable_file: "#8bcd5b" # Green
dir: "#41a7fc" # Blue

# Link
dead_link: "#f65866" # Red
link: "#34bfd0" # Cyan

# Special Files
socket: "#8bcd5b" # Green
blockdev: "#8bcd5b" # Green
chardev: "#8bcd5b" # Green

# Access Modes
write: "#8bcd5b" # Green
read: "#c75ae8" # Magenta
exec: "#34bfd0" # Cyan
no_access: "#f65866" # Red

# Age
hour_old: "#93a4c3" # Fg
day_old: "#455574" # Gray
no_modifier: "#93a4c3" # Fg

# File Size
file_large: "#f65866" # Red
file_medium: "#dd9046" # Orange
file_small: "#8bcd5b" # Green

# Random
report: "#8bcd5b" # Green
user: "#34bfd0" # Cyan
tree: "#c75ae8" # Magenta
empty: "#455574" # Gray
error: "#f65866" # Red
normal: "#93a4c3" # Fg

# Git
addition: "#34bfd0" # Cyan
modification: "#efbd5d" # Yellow
deletion: "#f65866" # Red
untracked: "#dd9046" # Orange
unchanged: "#8bcd5b" # Green
