# Main Colors
unrecognized_file: "#ae8a2c" # Yellow
recognized_file: "#869395" # Text
executable_file: "#88982d" # Green
dir: "#4689cc" # Blue

# Link
dead_link: "#ca4238" # Red
link: "#519e97" # Cyan

# Special Files
socket: "#88982d" # Green
blockdev: "#88982d" # Green
chardev: "#88982d" # Green

# Access Modes
write: "#88982d" # Green
read: "#c24380" # Magenta
exec: "#519e97" # Cyan
no_access: "#ca4238" # Red

# Age
hour_old: "#869395" # Text
day_old: "#5c6d74" # Gray
no_modifier: "#869395" # Text

# File Size
file_large: "#ca4238" # Red
file_medium: "#ae8a2c" # Yellow
file_small: "#88982d" # Green

# Random
report: "#88982d" # Green
user: "#519e97" # Cyan
tree: "#c24380" # Magenta
empty: "#5c6d74" # Gray
error: "#ca4238" # Red
normal: "#869395" # Text

# Git
addition: "#519e97" # Cyan
modification: "#ae8a2c" # Yellow
deletion: "#ca4238" # Red
untracked: "#ae8a2c" # Yellow
unchanged: "#88982d" # Green

