# colors ref: https://github.com/navarasu/onedark.nvim/blob/master/lua/onedark/palette.lua
# Main Colors
unrecognized_file: "#d99a5e" # Orange
recognized_file: "#a5b0c5" # Foreground
executable_file: "#97ca72" # Green
dir: "#5ab0f6" # Blue

# Link
dead_link: "#ef5f6b" # Red
link: "#4dbdcb" # Cyan

# Special Files
socket: "#97ca72" # Green
blockdev: "#97ca72" # Green
chardev: "#97ca72" # Green

# Access Modes
write: "#97ca72" # Green
read: "#ca72e4" # Magenta
exec: "#4dbdcb" # Cyan
no_access: "#ef5f6b" # Red

# Age
hour_old: "#a5b0c5" # Foreground
day_old: "#546178" # Comment
no_modifier: "#a5b0c5" # Foreground

# File Size
file_large: "#ef5f6b" # Red
file_medium: "#d99a5e" # Orange
file_small: "#97ca72" # Green

# Random
report: "#97ca72" # Green
user: "#4dbdcb" # Cyan
tree: "#ca72e4" # Magenta
empty: "#546178" # Comment
error: "#ef5f6b" # Red
normal: "#a5b0c5" # Foreground

# Git
addition: "#4dbdcb" # Cyan
modification: "#ebc275" # Yellow
deletion: "#ef5f6b" # Red
untracked: "#d99a5e" # Orange
unchanged: "#97ca72" # Green
