# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
# The minimal, blazing-fast, and infinitely customizable prompt
# Repo: https://starship.rs

# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# Inserts blank line between shell prompts
add_newline = true
command_timeout = 3000

# Configure the left prompt
format = """
$shell\
[](bg:rose fg:iris)\
$time\
[](bg:pine fg:rose)\
$directory\
[](bg:foam fg:pine)\
$git_branch\
[](bg:none fg:foam) \
"""

# Display language versions on the right prompt
right_format = """
$lua\
$nodejs\
$python\
"""

palette = "moon"

[palettes.main]
base = '#26233a'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ebbcba'
pine = '#31748f'
foam = '#9ccfd8'
iris = '#c4a7e7'

[palettes.moon]
base = '#222134'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ea9a97'
pine = '#3e8fb0'
foam = '#9ccfd8'
iris = '#c4a7e7'

[shell]
disabled = false
fish_indicator = "󰈺 "
powershell_indicator = "󰨊 "
zsh_indicator = "󱓞 zsh"
unknown_indicator = "mystery shell"
format = "[ $indicator ]($style)"
style = "bg:iris fg:base"

[time]
disabled = false
format = "[ 󱑁 $time ]($style)"
style = "bg:rose fg:base"
time_format = '%R'

[directory]
format = "[ 󰉋 $path ]($style)"
style = "bg:pine fg:base"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[ $symbol $branch ]($style)"
style = "bg:foam fg:base"
symbol = ""
truncation_length = 20

# Languages

[golang]
style = "bg:overlay fg:foam"
format = "[$symbol$version]($style) "
disabled = false
symbol = " "

[nodejs]
style = "bg:overlay fg:foam"
format = "[$symbol$version]($style) "
disabled = true
symbol = "󰚩 "

[rust]
style = "bg:overlay fg:foam"
format = "[$symbol$version]($style) "
disabled = false
symbol = "󱘗 "

[python]
style = "bg:overlay fg:foam"
format = "[$symbol$version]($style) "
disabled = false
symbol = " "

[conda]
style = "bg:overlay fg:foam"
format = "[$symbol$environment]($style) "
disabled = false
symbol = "🅒 "
