# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
# The minimal, blazing-fast, and infinitely customizable prompt
# Repo: https://starship.rs

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts blank line between shell prompts
add_newline = true
command_timeout = 3000

# Configure the left prompt
format = """
$username\
$directory\
$git_branch\
$character
"""

# Display language versions on the right prompt
right_format = """
$lua\
$nodejs\
$python\
"""

palette = "solarized"

[palettes.solarized]
aqua = '#2aa198'
black = "#0d2a34"
blue = '#268bd2'
green = '#859900'
orange = '#cb4b16'
purple = '#d33682'
violet = '#6c71c4'
white = '#ece8d6'
yellow = '#b58900'

[username]
show_always = true
style_user = "bg:purple fg:black"
style_root = "bg:purple fg:black"
format = '[](fg:purple)[󰀉 $user ]($style)[](bg:black fg:purple)'
disabled = false

[directory]
format = "[](bg:blue fg:black)[ 󰉋 $path ]($style)[](bg:black fg:blue)"
style = "bg:blue fg:black"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[](bg:aqua fg:black)[ $symbol $branch ]($style)[](bg:black fg:aqua)"
style = "bg:aqua fg:black"
symbol = ""

[character]
success_symbol = '[](bg:violet fg:black)[](bg: black fg:violet) '
error_symbol = '[](bg:orange fg:black)[](bg:black fg:red) '
format = "[$symbol]($style)"

# Languages

[golang]
style = "bg:overlay fg:aqua"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = " "

[nodejs]
style = "bg:overlay fg:aqua"
format = "[$symbol$version]($style) "
disabled = false
symbol = "󰚩 "

[rust]
style = "bg:overlay fg:aqua"
format = "[$symbol$version]($style) "
disabled = false
symbol = "󱘗 "

[python]
style = "bg:overlay fg:aqua"
format = "[$symbol$version]($style) "
disabled = false
symbol = ' '

[conda]
style = "bg:overlay fg:aqua"
format = "[$symbol$environment]($style) "
disabled = false
symbol = '🅒 '
