#!/usr/bin/env bash

set -euo pipefail

##? Setups the environment
#?? 1.0.0
##?
##? Usage:
##?    install

dotfiles_path="$HOME/.dotfiles"

echo "Cloning into: '$dotfiles_path'"
git clone --depth 1 git@github.com:jaumecapdevila/dotfiles.git "$dotfiles_path"

"$dotfiles_path/bin/dot" self install
