#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Remove a git branch
#?? 1.0.0
##?
##? Usage:
##?    remove-branch

docs::eval "$@"

if (! git::is_in_repo); then
  echo "Not in a git repo!"
  exit 0
fi

if (! git::is_main_branch); then
  echo "Checkout to the main branch to execute this command!"
  exit 0
fi

git branch | fzf --height 50% --ansi | awk -F ': ' '{print $1}' | xargs git branch -D
