# night
# color_bg="#16161e"
# color_fg="#787c99"
# color_border="#101014"
# color_selection="#515c7e4d"

# storm
color_bg="#1f2335"
color_fg="#7982a9"
color_border="#1b1e2e"
color_selection="#6f7bb635"

source "$tmux_themes_dir/shared.conf"
