# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
# The minimal, blazing-fast, and infinitely customizable prompt
# https://starship.rs

# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

# Inserts blank line between shell prompts
add_newline = true
command_timeout = 3000

format = """
$directory\
$line_break\
$character"""

right_format = """
$cmd_duration\
$git_branch\
$lua\
$nodejs\
$python"""

[directory]
format = "[ $path]($style) "
home_symbol = "~"
read_only = " 󰌾"
read_only_style = "red bold"
style = "blue bold"
truncate_to_repo = true
truncation_length = 2
truncation_symbol = '…/'

[git_branch]
disabled = false
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "cyan bold"
symbol = "󰘬 "
truncation_length = 20
truncation_symbol = "…"

[lua]
disabled = false
format = "[$symbol($version)]($style) "
style = "blue bold"
symbol = "󰽢 "

[nodejs]
disabled = false
format = "[$symbol($version)]($style) "
style = "green bold"
symbol = "󰚩 "

[python]
disabled = false
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
python_binary = "python3"
style = "yellow"
symbol = "󱔎 "

[cmd_duration]
format = '[$duration]($style) '
min_time = 2000
style = "yellow"

[line_break]
disabled = true

[character]
disabled = false
success_symbol = "[](purple)"
error_symbol = "[](red)"
vimcmd_symbol = "[](green)"
