# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
# The minimal, blazing-fast, and infinitely customizable prompt
# https://starship.rs

# Get editor completions based on the config schema
'$schema' = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 3000

format = """
$directory\
$git_branch\
$git_status\
$python\
$cmd_duration\
$character\
"""

[character]
disabled = false
success_symbol = "[](purple) "
error_symbol = "[](red) "
vimcmd_symbol = "[](green) "

[directory]
format = "[$path]($style) "
style = "blue bold"
truncate_to_repo = true
truncation_length = 2
truncation_symbol = ''

[git_branch]
disabled = false
format = '[$symbol$branch(:$remote_branch)]($style) '
style = 'cyan bold'
symbol = " "
truncation_length = 20
truncation_symbol = '…'

[git_status]
ahead = ' ${count}'
behind = ' behind=${count}'
conflicted = ' ${count} '
deleted = '󰍶 ${count} '
disabled = false
diverged = ' ${ahead_count}  ${behind_count}'
format = '[$all_status]($style)'
modified = '󰛿 ${count} '
renamed = '󱍸 ${count} '
staged = '󰐗 ${count} '
stashed = ' ${count} '
style = 'cyan bold'
untracked = '󰋗 ${count} '
up_to_date = ' '

[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style) '
python_binary = 'python3'
style = "yellow"
symbol = '󱔎 '

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

