# General config
add_newline = true

# Prompt segments
format = """
$character\
$directory\
$git_branch\
$line_break\
❯ """

[character]
success_symbol="[ ✓ ](bold fg:0 bg:229)"
error_symbol="[ ✗ ](bold fg:0 bg:229)"
format="$symbol($style)[\uE0B0](fg:229 bg:45)"

[directory]
format="[ $path ]($style)[\uE0B0](fg:45)"
truncation_length=2
truncation_symbol="../"
style="bold fg:0 bg:45"

[git_branch]
format="[\uE0B0](fg:black bg:238)[ $symbol$branch ]($style)[\uE0B0](fg:238)"
style="bold fg:87 bg:238"
