# General config
add_newline = true

# Prompt segments
format = """
$directory\
$git_branch\
$git_commit\
$line_break\
└─▪ """

[directory]
format="┌─[\\[$path\\]]($style)"
truncation_length=2
truncation_symbol=""
style="bold fg:125"

[git_branch]
symbol=""
format="[ \\[ $symbol $branch \\]]($style)"
style="bold fg:127"

[git_commit]
only_detached=false
tag_disabled=true
format="──[\\[ $hash \\]]($style)"
style="bold fg:129"
