# General config
add_newline = true

# Prompt segments
format = """
$character\
$battery\
$username\
$directory\
$git_branch"""

[character]
success_symbol="[ ✓ ](bold fg:0 bg:229)"
error_symbol="[ ✗ ](bold fg:0 bg:229)"
format="$symbol($style)[\uE0B0](fg:229 bg:193)"

[battery]
full_symbol=""
charging_symbol=""
discharging_symbol=""
format="[$symbol$percentage]($style)[\uE0B0](fg:193 bg:87)"

[[battery.display]]
threshold = 20
style = "bold fg:0 bg:193"

[[battery.display]]
threshold = 60
style = "bold fg:0 bg:193"

[[battery.display]]
threshold = 100
style = "bold fg:0 bg:193"

[username]
show_always=true
style_user="bold fg:0 bg:87"
style_root="bold fg:0 bg:87"
format="[ $user ]($style)[\uE0B0](fg:87 bg:45)"

[directory]
format="[ $path ]($style)[\uE0B0](fg:45) "
truncation_length=2
style="bold fg:0 bg:45"

[git_branch]
format="[\uE0B0](fg:bright-black bg:238)[ $symbol$branch ]($style)[\uE0B0](fg:238) "
style="bold fg:87 bg:238"
