# General config
add_newline = true

# Prompt segments
format = """
$character\
$directory\
$git_branch\
$line_break\
❯ """

[character]
success_symbol="[ ✓ ](bold fg:black bg:yellow)"
error_symbol="[ ✗ ](bold fg:black bg:yellow)"
format="$symbol($style)[\uE0B0](fg:yellow bg:blue)"

[directory]
format="[ $path ]($style)[\uE0B0](fg:blue)"
truncation_length=2
truncation_symbol="../"
style="bold fg:black bg:blue"

[git_branch]
format="[\uE0B0](fg:black bg:green)[ $symbol$branch ]($style)[\uE0B0](fg:green)"
style="bold fg:black bg:green"
