# General config
add_newline = true

# Prompt segments
format = """
$directory\
$git_branch\
"""

[directory]
format="[ $path ]($style)[\uE0B0](fg:blue) "
truncation_length=2
style="bold fg:black bg:blue"

[git_branch]
format="[\uE0B0](fg:black bg:green)[ $symbol$branch ]($style)[\uE0B0](fg:green) "
style="bold fg:black bg:green"
