user: "#bb9af7"
group: "#7aa2f7"
permission:
  read: "#9ece6a"
  write: "#e0af68"
  exec: "#f7768e"
  exec-sticky: "#bb9af7"
  no-access: "#a9b1d6"
  octal: "#73daca"
  acl: "#73daca"
  context: "#b4f9f8"
date:
  hour-old: "#73daca"
  day-old: "#b4f9f8"
  older: "#2ac3de"
size:
  none: "#a9b1d6"
  small: "#9ece6a"
  medium: "#e0af68"
  large: "#ff9e64"
inode:
  valid: "#f4b8e4"
  invalid: "#f7768e"
links:
  valid: "#f4b8e4"
  invalid: "#a9b1d6"
tree-edge: "#c0caf5"
git-status:
  default: "#c0caf5"
  unmodified: "#a9b1d6"
  ignored: "#a9b1d6"
  new-in-index: "#9ece6a"
  new-in-workdir: "#9ece6a"
  typechange: "#e0af68"
  deleted: "#f7768e"
  renamed: "#9ece6a"
  modified: "#e0af68"
  conflicted: "#f7768e"
