
# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
# The minimal, blazing-fast, and infinitely customizable prompt
# https://starship.rs

command_timeout = 1000
add_newline = true

# update default format
format = """
$character\
$directory\
$git_branch\
$nodejs\
$lua\
$cmd_duration\
$line_break"""

[line_break]
disabled = true

[directory]
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "~"
read_only_style = "red"
read_only = " 󰌾"
style = "bold blue"
format = "[󰉋 $path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "󰘬 "
format = "[$symbol$branch]($style) "
truncation_length = 10
truncation_symbol = "…/"
style = "bold purple"

[cmd_duration]
min_time = 2000
format = '[$duration](bold yellow) '

[python]
disabled = true
symbol = "󱔎"
style = "bold yellow"
python_binary = "python3"

[nodejs]
disabled = true
symbol = "󰚩 "
style = "bold green"
format = "[$symbol($version )]($style)"

[lua]
disabled = true
symbol = "󰽢 "
style = "bold blue"
format = "[$symbol($version )]($style)"

[status]
symbol = '[󰈸](red)'
success_symbol = '[󱓞](purple)'
format = '[$symbol]($style) '
disabled = true

[character]
disabled = false
success_symbol = '[󰬪](purple) '
error_symbol = '[󰬪](red) '

