
# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
# The minimal, blazing-fast, and infinitely customizable prompt
# https://starship.rs

# get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# inserts blank line between shell prompts
add_newline = true
command_timeout = 3000

# configure the format of the prompt
format = """
$username\
$directory\
$git_branch\
$lua\
$nodejs\
$python\
$cmd_duration\
$line_break\
$character"""

[username]
style_user = 'white bold'
style_root = 'black bold'
format = '[$user]($style) '
disabled = true
show_always = true
aliases = { "capdevil" = "jimmy" }

[directory]
format = "[󰉋 $path]($style) "
home_symbol = "~"
read_only = " 󰌾"
read_only_style = "bold red"
style = "bold blue"
truncate_to_repo = true
truncation_length = 2
truncation_symbol = "…/"

[git_branch]
disabled = false
format = "[$symbol$branch]($style) "
style = "bold purple"
symbol = "󰘬 "
truncation_length = 20
truncation_symbol = "…"

[lua]
disabled = false
format = "[$symbol($version )]($style)"
style = "bold blue"
symbol = "󰽢 "

[nodejs]
disabled = false
format = "[$symbol($version )]($style)"
style = "bold green"
symbol = "󰚩 "

[python]
disabled = false
format = "[$virtualenv]($style)"
python_binary = "python3"
style = "bold yellow"
symbol = "󱔎"

[cmd_duration]
format = '[$duration]($style) '
min_time = 2000
style = "bold yellow"

[line_break]
disabled = true

[character]
disabled = true
success_symbol = "[](green) "
error_symbol = "[](red) "
vimcmd_symbol = "[](green) "

