# UI config
font_family Operator Mono Book
bold_font Operator Mono Bold
italic_font Operator Mono Book Italic
bold_italic_font Operator Mono Bold Italic
font_size 20.0
# background_opacity 0.5

adjust_line_height 120%
cursor_blink_interval 0
disable_ligatures cursor
hide_window_decorations titlebar-only

window_border_width 0
window_margin_width 0
window_padding_width 4
remember_window_size  yes
confirm_os_window_close 0

# macOS config
macos_thicken_font 0.5
macos_show_window_title_in none
macos_option_as_alt left
macos_custom_beam_cursor no

# Other config
scrollback_lines 10000
enable_audio_bell no
allow_remote_control no

# Theme config
tab_bar_min_tabs 1
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template  " {title[title.rfind('/')+1:]} "

# Mappings

# https://sw.kovidgoyal.net/kitty/conf/#shortcut-kitty.Send-arbitrary-text-on-key-presses

# Use ctrl+shift+arrows in tmux
map ctrl+shift+right    no_op
map ctrl+shift+left     no_op

# fzf search
# map cmd+f launch --type=overlay --stdin-source=@screen_scrollback fzf --no-sort --no-mouse --exact -i

# less search
map cmd+f combine : show_scrollback : send_text normal,application /

# Open new tab in current directory
map cmd+t new_tab_with_cwd

# Move between tabs
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

# We use these in Neovim
map shift+enter send_text all \x1b[13;2u
map ctrl+enter send_text all \x1b[13;5u

# Jump to beginning and end of word.
map alt+left  send_text all \x1b\x62
map alt+right send_text all \x1b\x66

# Jump to beginning and end of line.
map cmd+left  send_text all \x05
map cmd+right send_text all \x05

# Ctrl and click to open a link
mouse_map ctrl+left press ungrabbed,grabbed mouse_click_url

# BEGIN_KITTY_THEME
include themes/tokyo/storm.conf
# END_KITTY_THEME
