#!/usr/bin/env zsh

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Prints the owner for a port
#?? 1.0.0
##?
##? Usage:
##?    port_owner <port>

docs::eval "$@"

lsof -nP -i4TCP:$1 | grep LISTEN
