#!/usr/bin/env bash

set -euo pipefail

source "$DOTFILES_PATH/scripts/core/_main.sh"

##? Stops the oms virtual machine
#?? 1.0.0
##?
##? Usage:
##?    ssh

docs::eval "$@"

cd $HOME/projects/magento/oms
vagrant halt
