# Automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on
set-option -g set-titles-string '#T'

# Enable mouse mode
set -g mouse on

# Setting the prefix from C-b to C-a
set -g prefix C-a

# Setting the delay between prefix and command
set -s escape-time 0

# STAR:clear_history
bind -n C-k clear-history

# Set the base index for windows to 1 instead of 0
set -g base-index 1

# Set the base index for panes to 1 instead of 0
setw -g pane-base-index 1

# Reload the file with Prefix r
bind r source-file ~/.tmux.conf \; display 'Reloaded'

# Toggle broadcast input
bind i setw synchronize-panes \; display 'Toggle panes sync'

# Splitting panes
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Set the default terminal mode to 256color mode
set -g default-shell /usr/local/bin/zsh
set -g default-terminal 'screen-256color'

# Enable activity alerts
setw -g monitor-activity on
set -g visual-activity on

# Move the status line to the top
set -g status on
set -g status-position 'top'

# Enable vi keys
setw -g mode-keys vi

# History limit
set -g history-limit 10000

# List of plugins
set -g @tpm_plugins '                     \
    arcticicestudio/nord-tmux            \
    tmux-plugins/tpm                      \
    tmux-plugins/tmux-sensible            \
    tmux-plugins/tmux-resurrect           \
    tmux-plugins/tmux-continuum           \
    tmux-plugins/tmux-yank                \
    tmux-plugins/tmux-pain-control        \
    tmux-plugins/tmux-copycat             \
    tmux-plugins/tmux-open                \
    tmux-plugins/tmux-prefix-highlight    \
'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
