#!/usr/bin/env zsh

source "$CONFIG_DIR/theme.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# https://felixkratz.github.io/SketchyBar/config/bar

bar=(
  color="$BAR_BACKGROUND"
  corner_radius="$RADIUS"
  height="$BAR_HEIGHT"
  margin="$BAR_MARGIN"
  padding_left="$BAR_PADDING"
  padding_right="$BAR_PADDING"
  position=top
  shadow=on
  sticky=on
  topmost=window
  y_offset="$BAR_OFFSET_TOP"
)

sketchybar --bar "${bar[@]}"

# Setting up default values
defaults=(
  background.border_width="$BORDER"
  background.corner_radius="$RADIUS"
  background.height="$ITEM_HEIGHT"
  icon.color="$ICON_COLOR"
  icon.font="$FONT_FACE:Bold:$FONT_SIZE"
  icon.padding_left="$ICON_PADDING"
  icon.padding_right="$ICON_PADDING"
  label.color="$BAR_FOREGROUND"
  label.font="$FONT_FACE:Medium:$FONT_SIZE"
  label.padding_left="$LABEL_PADDING"
  label.padding_right="$LABEL_PADDING"
  padding_left="$ITEM_PADDING"
  padding_right="$ITEM_PADDING"
  popup.background.border_color="$POPUP_BORDER_COLOR"
  popup.background.border_width="$BORDER"
  popup.background.color="$POPUP_BACKGROUND_COLOR"
  popup.background.corner_radius="$RADIUS"
  popup.background.shadow.drawing=on
  popup.blur_radius="$BLUR_LEVEL"
  scroll_texts=on
  updates=when_shown
)

sketchybar --default "${defaults[@]}"

# -- Left Side Items --
source "$ITEM_DIR/front_app.sh"

# -- Right Side Items --
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/brew.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
