#!/bin/bash

source "$CONFIG_DIR/theme.sh"

ITEM_DIR="$CONFIG_DIR/items" # Directory where the items are configured
PLUGIN_DIR="$CONFIG_DIR/plugins" # Directory where all the plugin scripts are stored

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

bar=(
  height=$BAR_HEIGHT
  color=$BAR_COLOR
  shadow=on
  position=top
  sticky=on
  padding_right=$BAR_PADDING
  padding_left=$BAR_PADDING
  y_offset=$GAP
  margin=$GAP
  corner_radius=$RADIUS
  topmost=window
)

sketchybar --bar "${bar[@]}"

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

defaults=(
  icon.font="$FONT:Bold:14.0"
  icon.color=$ICON_COLOR
  icon.padding_left=$ICON_PADDING
  icon.padding_right=$ICON_PADDING
  label.font="$FONT:Semibold:13.0"
  label.color=$LABEL_COLOR
  label.padding_left=$LABEL_PADDING
  label.padding_right=$LABEL_PADDING
  padding_right=$ITEM_PADDING
  padding_left=$ITEM_PADDING
  background.height=$ITEM_HEIGHT
  background.corner_radius=$RADIUS
)

sketchybar --default "${defaults[@]}"

# -- Left Side Items --

source $ITEM_DIR/calendar.sh

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuation loaded.."
