user: "#c792ea"
group: "#7986E7"
permission:
  read: "#a9c77d"
  write: "#ffcb6b"
  exec: "#ff869a"
  exec-sticky: "#c792ea"
  no-access: "#697098"
  octal: "#80cbc4"
  acl: "#80cbc4"
  context: "#8eace3"
date:
  hour-old: "#80cbc4"
  day-old: "#8eace3"
  older: "#82b1ff"
size:
  none: "#697098"
  small: "#a9c77d"
  medium: "#ffcb6b"
  large: "#f78c6c"
inode:
  valid: "#f4b8e4"
  invalid: "#697098"
links:
  valid: "#f4b8e4"
  invalid: "#697098"
tree-edge: "#b5bfe2"
git-status:
  default: "#697098"
  unmodified: "#697098"
  ignored: "#697098"
  new-in-index: "#a9c77d"
  new-in-workdir: "#a9c77d"
  typechange: "#ffcb6b"
  deleted: "#ff5874"
  renamed: "#a9c77d"
  modified: "#ffcb6b"
  conflicted: "#ff5874"
