# General config
add_newline = true

# Prompt segments
format = """
$directory\
$git_branch\
$git_status\
$git_commit\
$line_break\
❯ """

[directory]
format="[ $path ]($style)[\uE0B0](fg:blue)"
truncation_length=2
truncation_symbol=""
style="bold fg:black bg:blue"

[git_branch]
format="[\uE0B0](fg:black bg:238)[ $branch ]($style)"
style="bold fg:154 bg:238"

[git_status]
format="([$all_status$ahead_behind ]($style))"
style="bold fg:154 bg:238"

[git_commit]
only_detached=false
tag_disabled=true
format="[\uE0B0](fg:238 bg:244)[ $hash ]($style)[\uE0B0](fg:244)"
style="bold bg:244 fg:255"
